Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,17 +40,24 @@ jobs:
                 
       - name: Transfer Docker image to VM
         run: |
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
-          chmod 600 private_key
-          echo "Attempting SCP transfer..."
-          scp -v -o StrictHostKeyChecking=no -P 2222 -i private_key mmc-latest.tar.gz opc@${{ secrets.VM_HOST }}:/home/opc/mmc/
-          
-          echo "Checking VM directory..."
-          ssh -v -o StrictHostKeyChecking=no -p 2222 -i private_key opc@${{ secrets.VM_HOST }} "ls -l /home/opc/mmc/"
-          rm private_key
+            echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
+            chmod 600 private_key
+            echo "Attempting SCP transfer..."
+            scp -v -o StrictHostKeyChecking=no -P 2222 -i private_key mmc-latest.tar.gz opc@${{ secrets.VM_HOST }}:/home/opc/mmc/
+            
+            echo "Checking if file exists on VM..."
+            ssh -v -o StrictHostKeyChecking=no -p 2222 -i private_key opc@${{ secrets.VM_HOST }} "ls -l /home/opc/mmc/mmc-latest.tar.gz || { echo 'File not found!'; exit 1; }"
+            rm private_key
           
       - name: Deploy to VM
         uses: appleboy/ssh-action@v1.0.3
+        env:
+          DB_USER: ${{ secrets.DB_USER }}
+          DB_PASS: ${{ secrets.DB_PASS }}
+          SSL_PASS: ${{ secrets.SSL_PASS }}
+          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
+          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
+          OAUTH2_REDIRECT_URI: ${{ secrets.OAUTH2_REDIRECT_URI }}
         with:
           host: ${{ secrets.VM_HOST }}
           username: opc
